# .gitlab-ci.yml - Version 8 (Optimized)

# Define a hidden job template for AWS configuration
.aws_configure_template: &aws_configure
  before_script:
    - echo "Configuring AWS credentials..."
    - apt-get update -y && apt-get install -y awscli
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region $AWS_DEFAULT_REGION
    - echo "AWS configuration complete."

# Define the stages
stages:
  - prepare
  - validate
  - synth
  - diff
  - deploy

default:
  image: node:18
  tags:
    - docker

# --- Prepare Stage ---
install_deps:
  stage: prepare
  script:
    - npm ci
  cache:
    key:
      files: [package-lock.json]
    paths: [node_modules/]
    policy: pull-push

# --- Validate Stage ---
lint_code:
  stage: validate
  script:
    - npm run lint
  needs: [install_deps]
  cache:
    key:
      files: [package-lock.json]
    paths: [node_modules/]
    policy: pull

test_code:
  stage: validate
  script:
    - npm run test
  needs: [install_deps]
  cache:
    key:
      files: [package-lock.json]
    paths: [node_modules/]
    policy: pull

# --- Synth Stage ---
synthesize_template:
  stage: synth
  <<: *aws_configure # <-- Use the anchor alias
  script:
    - npm run build
    - npx cdk synth MagicmailInfraStack
  needs: [install_deps]
  cache:
    key:
      files: [package-lock.json]
    paths: [node_modules/]
    policy: pull
  artifacts:
    paths: [cdk.out/]
    expire_in: 1 day

# --- Diff Stage ---
preview_changes:
  stage: diff
  <<: *aws_configure # <-- Use the anchor alias
  script:
    - npm run build
    - npx cdk diff MagicmailInfraStack
  needs: [install_deps]
  cache:
    key:
      files: [package-lock.json]
    paths: [node_modules/]
    policy: pull

# --- Deploy Stage ---
deploy_app:
  stage: deploy
  <<: *aws_configure # <-- Use the anchor alias
  script:
    - npm run build
    - echo "Deploying CDK stack to AWS..."
    - npx cdk deploy MagicmailInfraStack --require-approval never
  needs: [preview_changes]
  cache:
    key:
      files: [package-lock.json]
    paths: [node_modules/]
    policy: pull
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
      allow_failure: false