# .gitlab-ci.yml - Version 9 (Adding Lint Stage for cfn-lint After synth)

# Define reusable AWS credential configuration
.aws_configure_template: &aws_configure
  before_script:
    - echo "Configuring AWS credentials..."
    - apt-get update -y && apt-get install -y awscli
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region $AWS_DEFAULT_REGION
    - echo "AWS configuration complete."

stages:
  - prepare
  - validate
  - synth
  - lint    # <-- NEW: Stage to validate synthesized CloudFormation template
  - diff
  - deploy

default:
  image: node:18
  tags:
    - docker

# --- Prepare Stage ---
install_deps:
  stage: prepare
  script:
    - npm ci
  cache:
    key:
      files: [package-lock.json]
    paths: [node_modules/]
    policy: pull-push

# --- Validate Stage ---
lint_code:
  stage: validate
  script:
    - npm run lint
  needs: [install_deps]
  cache:
    key:
      files: [package-lock.json]
    paths: [node_modules/]
    policy: pull

test_code:
  stage: validate
  script:
    - npm run test
  needs: [install_deps]
  cache:
    key:
      files: [package-lock.json]
    paths: [node_modules/]
    policy: pull

# --- Synth Stage ---
synthesize_template:
  stage: synth
  <<: *aws_configure
  script:
    - npm run build
    - npx cdk synth MagicmailInfraStack
  needs: [install_deps]
  cache:
    key:
      files: [package-lock.json]
    paths: [node_modules/]
    policy: pull
  artifacts:
    paths: [cdk.out/]
    expire_in: 1 day

# --- Lint Stage ---
# This MUST come after synth, because it runs on the output of `cdk synth` (in cdk.out)
lint_cfn_template:
  stage: lint
  <<: *aws_configure
  script:
    - echo "Installing cfn-lint..."
    # The node:18 image does not include Python by default
    - apt-get update && apt-get install -y python3 python3-pip
    - python3 -m pip install --break-system-packages cfn-lint
    - echo "Validating CloudFormation template..."
    - cfn-lint cdk.out/MagicmailInfraStack.template.json
  needs: [synthesize_template]
  cache:
    key:
      files: [package-lock.json]
    paths: [node_modules/]
    policy: pull

# --- Diff Stage ---
preview_changes:
  stage: diff
  <<: *aws_configure
  script:
    - npm run build
    - npx cdk diff MagicmailInfraStack
  needs: [install_deps]
  cache:
    key:
      files: [package-lock.json]
    paths: [node_modules/]
    policy: pull

# --- Deploy Stage ---
deploy_app:
  stage: deploy
  <<: *aws_configure
  script:
    - npm run build
    - npx cdk deploy MagicmailInfraStack --require-approval never
  needs: [preview_changes]
  cache:
    key:
      files: [package-lock.json]
    paths: [node_modules/]
    policy: pull
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
      allow_failure: false