# .gitlab-ci.yml - Simple Version 1 (Build Only)

stages:
 - build

default:
 image: node:18
 tags:
   - docker # Ensure jobs use our tagged Docker runner

build_app:
 stage: build
 script:
   - echo "Starting the build process inside $NODE_VERSION..."
   - node -v
   - npm -v
   - echo "Installing dependencies..."
   - npm ci
   - echo "Compiling TypeScript..."
   - npm run build
   - echo "Build finished!"