# .gitlab-ci.yml - Version 5 (Adding Diff Stage)

# Define the stages
stages:
  - prepare
  - validate
  - synth
  - diff     # <-- Add diff stage

default:
  image: node:18
  tags:
    - docker

# --- Prepare Stage ---
install_deps:
  # ... (job definition remains the same) ...
  stage: prepare
  script:
    - echo "Installing dependencies..."
    - npm ci
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
    policy: pull-push

# --- Validate Stage ---
lint_code:
  # ... (job definition remains the same) ...
  stage: validate
  script:
    - echo "Running linter..."
    - npm run lint
  needs: [install_deps]
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
    policy: pull

test_code:
  # ... (job definition remains the same) ...
  stage: validate
  script:
    - echo "Running unit tests..."
    - npm run test
  needs: [install_deps]
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
    policy: pull

# --- Synth Stage ---
synthesize_template:
  # ... (job definition remains the same) ...
  stage: synth
  before_script:
    - echo "Configuring AWS credentials for synth..."
    - apt-get update -y && apt-get install -y awscli
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region $AWS_DEFAULT_REGION
    - echo "AWS configuration complete."
  script:
    - echo "Compiling TypeScript (needed for synth)..."
    - npm run build
    - echo "Synthesizing CloudFormation templates..."
    - npx cdk synth MagicmailInfraStack
  needs: [install_deps]
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
    policy: pull
  artifacts:
    paths:
      - cdk.out/
    expire_in: 1 day

# --- Diff Stage --- <-- NEW STAGE & JOB

preview_changes:
  stage: diff
  before_script: # Also needs AWS credentials
    - echo "Configuring AWS credentials for diff..."
    - apt-get update -y && apt-get install -y awscli
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region $AWS_DEFAULT_REGION
    - echo "AWS configuration complete."
  script:
    - echo "Compiling TypeScript (needed for diff)..."
    - npm run build # Diff also needs compiled code
    - echo "Checking for infrastructure changes..."
    # Run cdk diff for the main stack
    - npx cdk diff MagicmailInfraStack
  needs: [install_deps] # Needs dependencies installed
                         # Could also depend on 'synthesize_template' if we used its artifacts
  cache: # Reuse the cache
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
    policy: pull
  # This job typically runs on all branches (including merge requests)
  # to allow reviewing changes before merge/deploy.
  # We'll refine rules later.